Repository reactos/wallpapers, pull requests merged in 2025-02, with the labels that each got.

#6 [WALLPAPERS] Compress Other/grass.jpg (1.9MB to 243KB)
  Others/grass.jpg
Labels: bug

#5 [WALLPAPERS] Update README.md for wallpapers manage
  README.md
  roswallp-sample.txt
Labels: documentation, enhancement

#7 [WALLPAPERS] Automate file size check
  README.md
  make-zip.sh
Labels: enhancement

#9 [WALLPAPERS] make-zip.sh: Display zip file size
  make-zip.sh
Labels: enhancement

#14 [WALLPAPERS] Update roswallp-sample.txt
  roswallp-sample.txt
Labels: enhancement

#15 [WALLPAPERS] Compress Other/Grass (719KB to 609KB)
  Others/CMakeLists.txt
  Others/Grass 3840x2560.jpg
  Others/Grass 4182x2788.jpg
  README.md
Labels: enhancement
